import copy
from types import SimpleNamespace
import urllib.parse

from tests.support import MigTestCase, testmain
from unittest import mock

from mig.server.createuser import _main as createuser
from mig.services.oidc import _create_service
from mig.shared.useradm import _USERADM_CONFIG_DIR_KEYS


EXAMPLE_CLIENT_OBJECT = SimpleNamespace(
    scopes=['openid'],
    distinguished_name='/C=DK/ST=NA/L=NA/O=Test Org/OU=NA/CN=Test User/emailAddress=user@example.com',
    client_id='user@example.com',
    response_type='code',
    redirect_uri='http://back.to/me',
    authorization_code='__AUTHORIZATION_CODE__',
)
EXAMPLE_CLIENT_ID = 'user@example.com'
EXAMPLE_USER_DN = '/C=DK/ST=NA/L=NA/O=Test Org/OU=NA/CN=Test User/emailAddress=user@example.com'


def _clear_userdb_related_state(configuration):
    test_state_path = configuration.state_path

    for config_key in _USERADM_CONFIG_DIR_KEYS:
        dir_path = getattr(configuration, config_key)[0:-1]
        try:
            shutil.rmtree(dir_path)
        except:
            pass


def _ensure_userdb_with_user(configuration):
    args = [
        "Test User",
        "Test Org",
        "NA",
        "DK",
        "user@example.com",
        "This is the create comment",
        "password"
    ]
    print("")  # acount for output generated by the logic
    createuser(configuration, args, default_renew=True)


class TestCase(MigTestCase):
    TEST_CLIENT_ID = EXAMPLE_CLIENT_ID
    TEST_USER_DN = EXAMPLE_USER_DN
    TEST_CLIENT_OBJECT = copy.deepcopy(EXAMPLE_CLIENT_OBJECT)
    TEST_CLIENT_OBJECT.authorization_code = 'abc'

    def _provide_configuration(self):
        return 'testconfig'

    def before_each(self):
        _clear_userdb_related_state(self.configuration)

    def test_server_creation_loads_user_db(self):
        _ensure_userdb_with_user(self.configuration)

        server, request_validator = _create_service(self.configuration)


        self.assertIsInstance(request_validator._user_db, dict)
        self.assertIn(self.TEST_USER_DN, request_validator._user_db)

    @mock.patch('oauthlib.common.generate_token', new=lambda: 'abc')
    def test_authorization_grant(self):
        _ensure_userdb_with_user(self.configuration)
        server, request_validator = _create_service(self.configuration)

        uri = 'http://i.b/l?' + urllib.parse.urlencode({
            'response_type': 'code',
            'client_id': 'user@example.com',
            'state': 'xyz',
            'redirect_uri': 'http://back.to/me',
        })
        headers, body, status_code = server.create_authorization_response(uri)

        self.assertIn('Location', headers)
        self.assertEqual(headers['Location'], 'http://back.to/me?code=abc&state=xyz')
        self.assertIn(self.TEST_CLIENT_ID, request_validator._saved)
        client = request_validator._saved[self.TEST_CLIENT_ID]
        print(client)
        self.assertEqual(client, self.TEST_CLIENT_OBJECT)


if __name__ == '__main__':
    testmain()
