#!/bin/bash
#
# apache2-mig-devs	Start the personal MiG developer apache HTTP servers.
#
# The variables below are NOT to be changed.  They are there to make the
# script more readable.

NAME=apache2

case "$1" in
  start | stop | reload | restart)
    for userdir in /etc/apache-*; do
    	login=`echo ${userdir}|sed 's@/etc/apache-@@g'`
	echo "${1}ing web server $NAME for developers: $login"
    	if [ ! -e /etc/$NAME-$login/apache-$login ]; then
	    # skip non MiG dev apache like apache-ssl
	    continue
	fi
    	if [ -x /etc/$NAME-$login/apache-$login ]; then
	    /etc/$NAME-$login/apache-$login $1
	else
	    logger "Error: apache-$login init script is not executable!"
	fi
    done
    ;;

  *)
    echo "Usage: $0 {start|stop|reload|restart}"
    exit 1
    ;;
esac

if [ $? -eq 0 ]; then
	echo .
	exit 0
else
	echo " failed"
	exit 1
fi
