#!/bin/bash
#
# run importdoi as mig user

# Add any custom domains to lookup DOIs for here and format according to
# https://support.datacite.org/docs/api-queries
# where we simply filter on our own FQDN in the registered DOI url.
doi_fqdn="url:" 

# No more edits below
su - mig -c "PYTHONPATH=/home/testuser/migrid mig/server/importdoi.py $doi_fqdn"

exit 0
