#!/bin/bash
#
# Run lustre quota for MiG servers
#
# The script depends on a miglustrequota setup
# (please refer to mig/src/pylustrequota/README).
#
# IMPORTANT: if placed in /etc/cron.X the script filename must be
# something consisting entirely of upper and lower case letters, digits,
# underscores, and hyphens. I.e. if the script name contains e.g. a period,
# '.', it will be silently ignored!
# This is a limitation on the run-parts wrapper used by cron
# (see man run-parts for the rationale behind this).

# By default bash silently ignores and continues on most errors but we can set
# options to e.g. catch uninitialized variables and errors as explained in:
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
# NOTE: 'set -eE' exits on non-zero exit codes to add safety and as recommended
# best-practice (CWE-252, CWE-248, ...), yet, in some cases it hurts more to
# exit midway, so it can be a trade-off.
set -eEuo pipefail

# Send output to another email address
#MAILTO="root"

MIG_CONF=/home/mig/mig/server/MiGserver.conf

# Specify if migrid runs natively or inside containers with lustre at host.
# Value is the container manager (docker, podman, or empty string for none)
container_manager=""
container="migrid-lustre-quota"

# Look in miglustrequota install dir first
export PATH="/usr/local/bin:${PATH}"

if [[ $(id -u) -ne 0 ]]; then
    echo "Please run $0 as root"
    exit 1
fi

if [ -z "${container_manager}" ]; then
    miglustrequota=$(which "miglustrequota.py" 2>/dev/null)
    if [ ! -x "${miglustrequota}" ]; then
        echo "ERROR: Missing miglustrequota.py"
        exit 1
    fi
    quota_cmd="${miglustrequota} -c ${MIG_CONF}" 
else
    check_cmd="${container_manager} container ls -a | grep -q '${container}'"
    eval "$check_cmd"
    ret=$?
    if [ "$ret" -ne 0 ]; then
        echo "ERROR: Missing ${container} container"
        exit 1
    fi
    quota_cmd="${container_manager} start -a ${container}"
fi

eval "$quota_cmd"
ret=$?

exit $ret
