name: Continuous Integration
on:
  # Triggers the workflow on push or pull request events but only for this git branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - experimental

  push:
    branches:
      - experimental

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read

jobs:
  python3-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Set up latest Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make test

  python3-rocky9:
    runs-on: ubuntu-22.04
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v3
      - name: Set up Python 3 and make with DNF
        run: |
          dnf install -y python3 python3-pip make
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make test

  python3-rocky8:
    runs-on: ubuntu-20.04
    container:
      image: rockylinux/rockylinux:8
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v3
      - name: Set up Python 3 and make with DNF
        run: |
          dnf install -y python3 python3-pip make
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make test

  python2-latest:
    runs-on: ubuntu-latest
    container:
      image: python:2
      volumes:
        - .:/usr/src/app
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          pip install --no-cache-dir -r requirements.txt -r local-requirements.txt
      - name: Run tests
        run: |
          PYTHON_BIN=python ./envhelp/makeconfig test --python2
          MIG_ENV='local' python -m unittest discover -s tests/
