name: Continuous Integration
on:
  # Triggers the workflow on push or pull request events but only for this git branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - experimental
      - next

  push:
    branches:
      - experimental
      - next

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read

jobs:
  # NOTE: We rely on containers for everything to get version consistency
  python3-latest:
    runs-on: ubuntu-latest
    container:
      image: python:3
      volumes:
        - .:/usr/src/app
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          make PYTHON_BIN=python3 dependencies
      - name: Run tests
        run: |
          make PYTHON_BIN=python3 unittest

  python3-rocky9:
    runs-on: ubuntu-22.04
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v3
      - name: Set up Python 3 and make with DNF
        run: |
          dnf install -y python3 python3-pip make
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make unittest

  python3-rocky8:
    runs-on: ubuntu-20.04
    container:
      image: rockylinux/rockylinux:8
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v3
      - name: Set up Python 3 and make with DNF
        run: |
          dnf install -y python3 python3-pip make
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make unittest

  python2-latest:
    runs-on: ubuntu-latest
    container:
      image: python:2
      volumes:
        - .:/usr/src/app
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          make PYTHON_BIN=python PY=2 dependencies
      - name: Run tests
        run: |
          make PYTHON_BIN=python PY=2 unittest
