# This workflow will install Python dependencies and run internal tests with a representative selection of OS and Python platforms
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Continuous Integration

on:
  # Triggers the workflow on push or pull request events but only for this git branch
  push:
    paths-ignore:
      - 'README'
      - 'COPYING'
      - 'NEWS'
      - '*.txt'
      - 'doc/**'
      - 'doc-src/**'
      - 'user-projects/**'
      - 'state/**'
      - 'certs/**'
      - 'MiG-certificates/**'
      - 'mig/images/**'
      - 'mig/assets/**'
      - 'mig/src/**'
      - 'mig/apache/**'
      - 'mig/bin/**'
      - 'mig/java-bin/**'
    branches:
      - edge
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README'
      - 'COPYING'
      - 'NEWS'
      - '*.txt'
      - 'doc/**'
      - 'doc-src/**'
      - 'user-projects/**'
      - 'state/**'
      - 'certs/**'
      - 'MiG-certificates/**'
      - 'mig/images/**'
      - 'mig/assets/**'
      - 'mig/src/**'
      - 'mig/apache/**'
      - 'mig/bin/**'
      - 'mig/java-bin/**'
    branches:
      - edge
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # NOTE: We rely on containers for everything to get version consistency
  python3-latest:
    name: Run internal tests in latest stable python3
    runs-on: ubuntu-latest
    container:
      image: python:3
      volumes:
        - .:/usr/src/app
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          make PYTHON_BIN=python3 dependencies
      - name: Run tests
        run: |
          make PYTHON_BIN=python3 unittest

  python3-rocky9:
    name: Run internal tests in default python3 on Rocky9
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Set up Python 3 and make with DNF
        run: |
          dnf install -y python3 python3-pip make
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make unittest

  python3-rocky8:
    name: Run internal tests in default python3 on Rocky8
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Set up Python 3 and make with DNF
        run: |
          dnf install -y python3 python3-pip make
      - name: Setup environment
        run: |
          make dependencies
      - name: Run tests
        run: |
          make unittest

  python2-latest:
    name: Run internal tests in latest stable python2
    runs-on: ubuntu-latest
    container:
      image: python:2
      volumes:
        - .:/usr/src/app
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          make PYTHON_BIN=python PY=2 dependencies
      - name: Run tests
        run: |
          make PYTHON_BIN=python PY=2 unittest
