name: Python Style Checks

on:
  push:
    branches:
      - edge
      - main
  pull_request:
    branches:
      - edge
      - main

jobs:
  stylecheckpython:
    name: Style Check Python with Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This is necessary to get the commits
      - name: Get changed python files between base and head
        run: >
          echo "CHANGED_FILES=$(echo $(git diff  --diff-filter=ACMRTB --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- | grep -E '\.py$'))" >> $GITHUB_ENV
      - if: ${{ env.CHANGED_FILES }}
        uses: marian-code/python-lint-annotate@v4
        with:
          python-root-list: ${{ env.CHANGED_FILES }}
          extra-pycodestyle-options: "--max-line-length=80"
          extra-isort-options: "-m=HANGING_INDENT"
          # NOTE: we disable flake8 and pylint here to avoid overlap with lint action and limit noise
          use-flake8: false
          extra-flake8-options: "--max-line-length=80"
          use-pylint: false
          # NOTE: pylint C0209 string format suggestions requires python3.6+ so disable here
          # https://pylint.pycqa.org/en/latest/user_guide/messages/convention/consider-using-f-string.html
          extra-pylint-options: "--disable=C0209" 
